languageCode = "en-us"
title = "Github Page"
baseurl = "https://raquel.github.io/"
theme = "aerial"

[params]
  name = "Raquel Lira"
  about = "Software Engineer &nbsp;&bull;&nbsp; Planeswalker  &nbsp;&bull;&nbsp; Testing Hugo with Github"
  copyright = ""
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/raqueIIira"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://facebook.com/raquel.lira.750"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/raquellira/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/raquel"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:raquel.lira@gmail.com"
